version: '3.8'

services:
  studio:
    container_name: supabase-studio
    image: supabase/studio:20250113-6447c23
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD-SHELL', 'wget --no-verbose --spider --tries=1 --timeout=5 http://localhost:3000/api/profile || exit 1' ]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - '${STUDIO_PORT}:3000'
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SUPABASE_URL: http://kong:8000
      SUPABASE_PUBLIC_URL: ${SUPABASE_PUBLIC_URL}
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
      LOGFLARE_API_KEY: ${LOGFLARE_API_KEY:-}
      LOGFLARE_URL: http://analytics:4000
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    depends_on:
      - meta

  kong:
    container_name: supabase-kong
    image: kong:2.8.1
    restart: unless-stopped
    ports:
      - '${KONG_HTTP_PORT}:8000'
      - '${KONG_HTTPS_PORT}:8443'
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      # Default is http://localhost:8001
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
    volumes:
      - ./volumes/api/kong.yml:/var/lib/kong/kong.yml:ro
    depends_on:
      - auth
      - rest
      - realtime
      - storage
      - meta

  auth:
    container_name: supabase-auth
    image: supabase/gotrue:v2.132.3
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD-SHELL', 'wget --no-verbose --spider --tries=1 --timeout=5 http://localhost:9999/health || exit 1' ]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${API_EXTERNAL_URL}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://supabase_auth_admin:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      GOTRUE_SITE_URL: ${SITE_URL}
      GOTRUE_URI_ALLOW_LIST: ${ADDITIONAL_REDIRECT_URLS}
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: ${JWT_EXPIRY}
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_RATES_LIMIT: 1000
      GOTRUE_RATES_WINDOW: 60
      GOTRUE_DISABLE_SIGNUP: ${DISABLE_SIGNUP}
      GOTRUE_MAILER_AUTOCONFIRM: 'true'
      # GOTRUE_SMS_AUTOCONFIRM: "true"
      # GOTRUE_OTP_EXP: 86400
      # GOTRUE_OTP_LENGTH: 6
    depends_on:
      - db

  rest:
    container_name: supabase-rest
    image: postgrest/postgrest:v12.2.0
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD-SHELL', 'head -n 1 /dev/tcp/127.0.0.1/3000 || exit 1' ]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      PGRST_DB_URI: postgres://authenticator:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PGRST_DB_SCHEMAS: public,storage,graphql
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: 'false'
    depends_on:
      - db

  realtime:
    container_name: supabase-realtime
    image: supabase/realtime:v2.33.58
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD-SHELL', "bash -c ':> /dev/tcp/127.0.0.1/4000' || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: supabase_admin
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_AFTER_CONNECT_QUERY: 'SET search_path TO _realtime'
      DB_ENC_KEY: supabaserealtime
      API_JWT_SECRET: ${JWT_SECRET}
      FLY_ALLOC_ID: fly
      API_JWT_AUTHTOKEN: ${SERVICE_ROLE_KEY}
      # ERLANG_COOKIE: "Cookie"
      # SECRET_KEY_BASE: "KEY"
      # SECURE_SESSION: "false"
    depends_on:
      - db

  storage:
    container_name: supabase-storage
    image: supabase/storage-api:v1.11.13
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD-SHELL', 'wget --no-verbose --spider --tries=1 --timeout=5 http://localhost:5000/status || exit 1' ]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      ANON_KEY: ${ANON_KEY}
      SERVICE_KEY: ${SERVICE_ROLE_KEY}
      POSTGRES_DATAWAREHOUSE_URL: postgres://supabase_storage_admin:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      POSTGRES_TENANT_URL: postgres://supabase_storage_admin:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: ${TENANT_ID}
      REGION: local
      GLOBAL_S3_BUCKET: stub
      PGRST_JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://supabase_storage_admin:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: ${STORAGE_BACKEND}
    volumes:
      - ./volumes/storage:/var/lib/storage
    depends_on:
      - db
      - imgproxy

  imgproxy:
    container_name: supabase-imgproxy
    image: darthsim/imgproxy:v3.26.0
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD-SHELL', 'head -n 1 /dev/tcp/127.0.0.1/8080 || exit 1' ]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      IMGPROXY_BIND: :5001
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /
      IMGPROXY_USE_ETAG: 'true'
      IMGPROXY_ENABLE_WEBP_DETECTION: 'true'
      IMGPROXY_MALLOC: jemalloc
      IMGPROXY_SO_REUSEPORT: 'true'
      IMGPROXY_GZIP_COMPRESSION: 0
      IMGPROXY_COST_TIMER: 0
      IMGPROXY_LOG_FORMAT: json
      IMGPROXY_LOG_LEVEL: info
      IMGPROXY_MAX_ANIMATION_FRAMES: 1

  meta:
    container_name: supabase-meta
    image: supabase/postgres-meta:v0.84.2
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD-SHELL', 'wget --no-verbose --spider --tries=1 --timeout=5 http://localhost:8080/health || exit 1' ]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: ${POSTGRES_DB}
      PG_META_DB_USER: supabase_admin
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db

  functions:
    container_name: supabase-requests
    image: supabase/edge-runtime:v1.54.3
    restart: unless-stopped
    ports:
      - '54321:54321'
    environment:
      SUPABASE_URL: http://kong:8000
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}
      POSTGRES_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./functions:/home/deno/functions
    depends_on:
      - db
      - kong

  db:
    container_name: supabase-db
    image: supabase/postgres:15.6.1.141
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres -h 127.0.0.1' ]
      interval: 5s
      timeout: 5s
      retries: 10
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      # - -c
      # - log_min_messages=fatal # Reduces log verbosity
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
      - ./volumes/db/init:/docker-entrypoint-initdb.d
      # Mount the project schema to be auto-applied on fresh install
      - ../supabase_schema.sql:/docker-entrypoint-initdb.d/init-project.sql

  postfix:
    container_name: supabase-postfix
    image: boky/postfix
    restart: always
    ports:
      - '2525:25'
    environment:
      RELAYHOST: smtp.gmail.com:587
      SMTP_LOGIN: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      ALLOWED_SENDER_DOMAINS: '*'
      MYHOSTNAME: pettycash.local

volumes:
  db-data:
